$activeBorderColor = rgb(7eae81)
$activeShadowColor = rgb(7eae81)
$inactiveBorderColor = rgba(2c2c2c99)
$inactiveShadowColor = rgba(7eae8177)

general {
    col.active_border = $activeBorderColor
    col.inactive_border = $inactiveBorderColor
    gaps_in = 6
    gaps_out = 12
}

group {
    col.border_active = $activeBorderColor
    col.border_inactive = $inactiveBorderColor
}

windowrule = opacity 0.88 0.78, match:tag terminal

decoration {
    shadow {
        enabled = true
        range = 12
        render_power = 4
        color = $activeShadowColor
        color_inactive = $inactiveShadowColor
    }
}
